version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  super8festivals:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ./super8festivals-omeka-plugin:/var/www/html/plugins/SuperEightFestivals/
      - ./super8festivals-omeka-theme:/var/www/html/themes/SuperEightFestivals/
